## This workflow is triggered on pushes to the main branch and deploys the application
# to a remote server using SSH and Docker Compose.

name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/gg-cicd-forum-api
            git pull origin main
            cd gg-forum-api
            npm install
            npm run migrate up
            pm2 restart gg-forum-api
