# This workflow is used to run tests on pull requests to ensure that the code is functioning correctly before merging into the main branch.

name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.PGUSER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          cd gg-forum-api
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          HOST: ${{ secrets.HOST_TEST }}
          PORT: ${{ secrets.PORT_TEST }}
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          PGUSER: ${{ secrets.PGUSER_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY_TEST }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY_TEST }}
          ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE_TEST }}
